### ISSUE TITLE
Dependency version numbers

### ISSUE THREAD

**Issue by dzeigler** [cecom/pomutils#10]
I have a multi-module maven project where a module can have other modules as dependencies for packaging purposes. For example:
```
root
├── Module A
├── Module B
└── Module C
    └── dependencies include Module A and Module B
```
Module C's pom contains something like:
```xml
<dependencies>
	<dependency>
		<groupId>com.example</groupId>
		<artifactId>module-a</artifactId>
		<version>2.0.3-SNAPSHOT</version>
	</dependency>
	<dependency>
		<groupId>com.example</groupId>
		<artifactId>module-b</artifactId>
		<version>2.0.3-SNAPSHOT</version>
	</dependency>
</dependencies>
```
Anytime there is a release, the maven release plugin increments the pom's project versions and these dependency versions automatically.

The pomutils driver handles conflicts with each pom's project version, but these dependency versions in Module C are still conflicting during merges. Would it be possible add support for this case to pomutils? Or is there something I should do at the ruleset level to avoid the conflicts on the dependencies?

Thanks

**Comment by cecom** [comment]
I dont use the release plugin, but can't you do the following...

Your pom version is 

```
<pom>
   <version>2.0.3-SNAPSHOT</version>
    ...

```
when you now use this in your dependency section: 

```
<dependencies>
	<dependency>
		<groupId>com.example</groupId>
		<artifactId>module-a</artifactId>
		<version>${pom.version}</version>
	</dependency>
	<dependency>
		<groupId>com.example</groupId>
		<artifactId>module-b</artifactId>
		<version>${pom.version}</version>
	</dependency>
</dependencies>
```

and tell the release plugin "updateDependencies=false", that should solve the merge problem.

**Comment by dzeigler** [comment]
Thanks. That did exactly what I was wanting.
