### ISSUE TITLE
logger not declared lead to NPE

### ISSUE THREAD

**Issue by sirnono** [cecom/pomutils#14]
below logger.debug line can lead to NPE if logger declaration not reached.
First initialize the logger or use System.out.

From Main.java

        private static Logger logger = null;

	public static void main(String... args) {
		int resultValue = 0;
		try {
			resultValue = mainInternal(args);
		} catch (Exception e) {
			System.err.println("We got an exception on merge: " + StringUtils.join(args, " "));
			e.printStackTrace();
			System.exit(1);
		}
		logger.debug("Exiting with exit code {}", resultValue);
		System.exit(resultValue);
	}

**Comment by cecom** [comment]
Sorry for fixing it so late. Fixed it with the 1.7.0.
