### ISSUE TITLE
Problem during merge with removed maven modules in development branch

### ISSUE THREAD

**Issue by grossmane** [cecom/pomutils#17]
Hi Sven,

we have one problem with pomutils, but we have not a good solutions to solve it, maybe you have an idea.

We have the following scenario:
Gitflow branching model, with development, release and final master branch.

1) We start a release from development (Snapshotversion from development moved to release branch and in development branch the minor version will be increased)
2) In development branch we remove a maven module with pom.xml
3) Now we want finish the release
* Release will be merged to master
* Version in master will be updated to final version (remove the snapshot version)
* And after that we want merge the master branch to development
4) During this merge we get the error, that the pom.xml from the removed modul was removed and pomutils didn't have an idea how it should solve.
5) The error is valid, because in git history we have an change in master branch for that pom.xml (We update the version from snapshot to final) and in development branch we have the  update, that the module with the pom.xml was removed. pomutils can compare the pom.xml and we get this error.

Maybe it is an option, that we have an argument for pomutils to allow that case, that the pom.xml is missing on target side and I can approve this case with this argument.

many regards,
Jens Großmann

**Comment by cecom** [comment]
Hi Jens,

ok, i understand. I think,that is a bug of pomutils. I try to reproduce it in a test. And try to fix it.

Could you plz send me a reproducer? I think i understood it, but to be sure :)

**Comment by cecom** [comment]
Here is my [reproducer](https://github.com/cecom/pomutils/files/4776269/reproducer.zip). Is that correct?

Unpack and you will find 3 branches:

- develop  --> containing 1.2.0-SNAPSHOT
- release/1.1.0 --> containing 1.1.0-SNAPSHOT
- master --> containing 1.1.0

in develop the modul2 is removed. If you try now to merge the master branch to develop, you get your error you are talking about. Right?

And there is the problem. Git does not call pomutils for that module2 merge conflict. So i can't fix that.

**Comment by grossmane** [comment]
Hi Sven,

ah yes, I understand. You are right. Git does not call pomutils for deleted pom.xml.

I think we can close this issue. We will look internally, how we can handle this case.

br
Jens
